name: Development

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build . -t willebergh/mega-mailer:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image
        run: docker push willebergh/mega-mailer:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Update server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CD_SERVER_HOST }}
          username: ${{ secrets.CD_SERVER_USERNAME }}
          password: ${{ secrets.CD_SERVER_PASSWORD }}
          script: ~/mega/update_mailer.sh
